### ISSUE TITLE
Link to alfred workflow is broken

### ISSUE THREAD

**Issue by gbstan** [vitorgalvao/sandwichtimer#1]
Hi Vitor,

I would be interested in a simple to use pomodoro-type timer. It looks like, once again, you are ahead of the curve and have already developed one with sandwichtimer. I was particularly interested in the alfred workflow, but it seems that the link to the alfred workflow is not working: https://github.com/vitorgalvao/alfred-workflows/tree/master/SandwichTimer

Is it just the link that is not working, or am I too impatient and the alfred workflow is not ready yet?

Cheers,

Guy

**Comment by vitorgalvao** [comment]
The Workflow has been working for a while, but I haven’t released it yet. Still have to introduce a way to download the SandwichTimer app, and write the documentation.

[Here’s a provisional one](https://transfer.sh/CYZcV/SandwichTimer.alfredworkflow).

**Comment by gbstan** [comment]
Hi Vitor,

Many thanks,

I have tried to open the zip file you attached but there appears to only be two files in it:

    info.plist
    icon.png

I am missing something?

With my best regards,

Guy

**Comment by vitorgalvao** [comment]
It’s not a zip, but a .alfredworkflow (which technically is a zip with a different extension).

If it’s opening as a zip, try to see if there’s something wrong with the extension.

**Comment by gbstan** [comment]
Got it and installed it. It works.
I was confused as the link downloaded the file with the extension .zip. After replacing .zip with .alfredworkflow it worked correctly.

**Comment by vitorgalvao** [comment]
I’ve released the Workflow, so the link is now working. You should update to that version, since it has auto-updating built-in.

**Comment by gbstan** [comment]
Super! I have already updated and installed the app too.

I suppose the app is also auto-updating?

**Comment by vitorgalvao** [comment]
> I suppose the app is also auto-updating?

It is not. Electron’s documentation suggests apps need to be code-signed to have auto-updating capabilities, and I can’t really justify the cost for a macOS developer account.

**Comment by gbstan** [comment]
Fair enough.

**Comment by gbstan** [comment]
I have been using sandwichtimer since your release it. It is really 
great! Simple and useful.

One thing that I am wondering is if it would be possible to have a 
toggle for playing a sound (or not) when the timer is done.

That would allow to broaden the use cases (at least for me).

**Comment by vitorgalvao** [comment]
It already plays a sound when it’s done. If you `afplay /System/Library/Sounds/Blow.aiff` you’ll hear what it is.

**Comment by gbstan** [comment]
Yes, I use it this way for the moment with this sound. My question was 
more on the possibility of choosing the sound and switching it on or off.

**Comment by vitorgalvao** [comment]
> choosing the sound

That’s unlikely to happen. It’d require building an entire settings screen or a weird sub-menu. Too much trouble for working for free on a feature few would use.

> switching it on or off

That might happen, but no promises. There are other things it’d like for the app to have before that.

**Comment by gbstan** [comment]
Fair enough. I agree with you.
