### ISSUE TITLE
"SandwichTimer" can't be opened

### ISSUE THREAD

**Issue by bzreinhardt** [vitorgalvao/sandwichtimer#2]
I tried using the latest zipped version and got this error - not even sure how to poke it. 

On OSX 10.15.2 (19C57)

![image](https://user-images.githubusercontent.com/5651270/72229366-01ad2d00-35e9-11ea-8b1c-c3d7657d2777.png)

**Comment by vitorgalvao** [comment]
Does it work if you right-click and pick `Open`?

**Comment by vitorgalvao** [comment]
Closing for lack of reply.

**Comment by 0xhiroki** [comment]
Hi, I have the same issue here.

Right-clicking and picking open didn't work for me.

macOS Catalina 10.15.6

**Comment by vitorgalvao** [comment]
> Right-clicking and picking open didn't work for me.

I’m not able to respond with “didn’t work”. I need detailed steps of what you did and what happened or didn’t.

> macOS Catalina 10.15.6

But I’m not on Catalina and won’t be. I’ll take a decent PR to fix an issue but I don’t have the resources to spend on debugging this for free.

**Comment by 0xhiroki** [comment]
> I’m not able to respond with “didn’t work”. I need detailed steps of what you did and what happened or didn’t. 

My bad, I should have elaborated it a bit. When I selected "open", I saw the same message 'The Application "SandwichTimer" cannot be opened.' I didn't debug it, so I'm not sure what's causing it under the hood. My guess is that it's an issue on Catalina. 

> But I’m not on Catalina and won’t be. I’ll take a decent PR to fix an issue but I don’t have the resources to spend on debugging this for free.

I might take a look at the code and debug it in my free time.

**Comment by vitorgalvao** [comment]
> I might take a look at the code and debug it in my free time.

My recommendation would be to update the Electron dependency to the most recent version and fixing whatever breaks. Electron is great to hit the ground running and has superb documentation, but they deprecate and change things so often that maintaining a functioning app becomes a chore.
