### ISSUE TITLE
Faded appearance in menu bar

### ISSUE THREAD

**Issue by Neberheim** [vitorgalvao/sandwichtimer#5]
I recently reinstalled Alfred and the Sandwich timer on a clean MacOS install, and now SandwichTimer always displays with a subdued icon and text in the menubar.

Expected behavior is that the timer is fully visible in the menu bar. I believe this was the behavior prior to installation on the new system, although I'm not able to verify that myself.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/39180248/92967895-a5343300-f43f-11ea-9ca5-e34cde89f6b5.png">

**Comment by vitorgalvao** [comment]
What’s your macOS version?

**Comment by Neberheim** [comment]
MacOS 10.15.6
Alfred 4.1.1 [1172]
SandwichTimer 20.2

**Comment by vitorgalvao** [comment]
Unfortunately, I’m still on Mojave. That smells like something caused by Catalina.

I’ll take a PR to fix it and update the dependencies, but cannot test on Catalina.

**Comment by vitorgalvao** [comment]
Might be fixed by #6. Uploading the new release build now.
